<?php

	// Portfolio
	define('PORTFOLIO_TITLE', 'PORTFOLIO_TITLE');
	define('PORTFOLIO_SUBTITLE', 'PORTFOLIO_SUBTITLE');
	define('PORTFOLIO_PRIVATE_TAB', 'PORTFOLIO_PRIVATE_TAB');
	define('PORTFOLIO_PROFESSIONAL_TAB', 'PORTFOLIO_PROFESSIONAL_TAB');
	define('PORTFOLIO_BACK_TAB', 'PORTFOLIO_BACK_TAB');
	define('PORTFOLIO_UNLOCK_PROJECT_TITLE', 'PORTFOLIO_UNLOCK_PROJECT_TITLE');
	define('PORTFOLIO_UNLOCK_TITLE', 'PORTFOLIO_UNLOCK_TITLE');
	define('PORTFOLIO_UNLOCK_DESCRIPTION', 'PORTFOLIO_UNLOCK_DESCRIPTION');
	define('PORTFOLIO_UNLOCK_LABEL', 'PORTFOLIO_UNLOCK_LABEL');
	define('PORTFOLIO_UNLOCK_PLACEHOLDER', 'PORTFOLIO_UNLOCK_PLACEHOLDER');
	define('PORTFOLIO_UNLOCK_SUBMIT', 'PORTFOLIO_UNLOCK_SUBMIT');
	define('PORTFOLIO_UNLOCK_INVALID', 'PORTFOLIO_UNLOCK_INVALID');
	define('PORTFOLIO_BOTTOM_BACK', 'PORTFOLIO_BOTTOM_BACK');

	// Comic
	define('COMIC_NO_EPISODES', 'COMIC_NO_EPISODES');
	define('COMIC_NAV_FIRST', 'COMIC_NAV_FIRST');
	define('COMIC_NAV_PREVIOUS', 'COMIC_NAV_PREVIOUS');
	define('COMIC_NAV_NEXT', 'COMIC_NAV_NEXT');
	define('COMIC_NAV_LAST', 'COMIC_NAV_LAST');
	define('COMIC_ARCHIVE_HEADLINE', 'COMIC_ARCHIVE_HEADLINE');
	define('COMIC_ARCHIVE_SUBTITLE', 'COMIC_ARCHIVE_SUBTITLE');

	// Footer
	define('FOOTER_CONTACT_HEAD', 'FOOTER_CONTACT_HEAD');
	define('FOOTER_MAIL', 'FOOTER_MAIL');
	define('FOOTER_DISCORD', 'FOOTER_DISCORD');
	define('FOOTER_DISCORD_SERVER', 'FOOTER_DISCORD_SERVER');
	define('FOOTER_SOCIAL_HEAD', 'FOOTER_SOCIAL_HEAD');
	define('FOOTER_LEGAL_HEAD', 'FOOTER_LEGAL_HEAD');
	define('FOOTER_LEGAL', 'FOOTER_LEGAL');
	define('FOOTER_DATA', 'FOOTER_DATA');
	define('FOOTER_LICENSE', 'FOOTER_LICENSE');

	// Cookie Banner
	define('COOKIE_TITLE_TEXT', 'COOKIE_TITLE_TEXT');
	define('COOKIE_CONSENT_TEXT', 'COOKIE_CONSENT_TEXT');
	define('COOKIE_ACCEPT_TEXT', 'COOKIE_ACCEPT_TEXT');

	// Options
	define('ADMIN_TITLE', 'ADMIN_TITLE');
	define('ADMIN_MENU', 'ADMIN_MENU');
	define('ADMIN_MAIN_TITLE', 'ADMIN_MAIN_TITLE');
	define('ADMIN_MAIN_MENU', 'ADMIN_MAIN_MENU');
	define('ADMIN_BLOG_TITLE', 'ADMIN_BLOG_TITLE');
	define('ADMIN_BLOG_MENU', 'ADMIN_BLOG_MENU');
	define('ADMIN_CAST_TITLE', 'ADMIN_CAST_TITLE');
	define('ADMIN_CAST_MENU', 'ADMIN_CAST_MENU');
	define('ADMIN_EPISODES_TITLE', 'ADMIN_EPISODES_TITLE');
	define('ADMIN_EPISODES_MENU', 'ADMIN_EPISODES_MENU');
	define('ADMIN_MEDIA_LIBRARY_USE', 'ADMIN_MEDIA_LIBRARY_USE');
	define('ADMIN_OPTIONS', 'ADMIN_OPTIONS');
	define('ADMIN_GENERAL', 'ADMIN_GENERAL');
	define('ADMIN_SOCIAL_BUTTON_COUNT', 'ADMIN_SOCIAL_BUTTON_COUNT');
	define('ADMIN_SOCIAL_BUTTON_IMAGE_SIZE', 'ADMIN_SOCIAL_BUTTON_IMAGE_SIZE');
	define('ADMIN_SOCIAL_BUTTON_LABEL', 'ADMIN_SOCIAL_BUTTON_LABEL');
	define('ADMIN_SOCIAL_BUTTON_DESCRIPTION', 'ADMIN_SOCIAL_BUTTON_DESCRIPTION');
	define('ADMIN_SOCIAL_BUTTON_GRAPHICS', 'ADMIN_SOCIAL_BUTTON_GRAPHICS');
	define('ADMIN_SOCIAL_BUTTON_UP_IMAGE', 'ADMIN_SOCIAL_BUTTON_UP_IMAGE');
	define('ADMIN_SOCIAL_BUTTON_DOWN_IMAGE', 'ADMIN_SOCIAL_BUTTON_DOWN_IMAGE');
	define('ADMIN_SOCIAL_BUTTON_URL_EN', 'ADMIN_SOCIAL_BUTTON_URL_EN');
	define('ADMIN_SOCIAL_BUTTON_URL_DE', 'ADMIN_SOCIAL_BUTTON_URL_DE');
	define('ADMIN_SOCIAL_BUTTON_DESCRIPTION_EN', 'ADMIN_SOCIAL_BUTTON_DESCRIPTION_EN');
	define('ADMIN_SOCIAL_BUTTON_DESCRIPTION_DE', 'ADMIN_SOCIAL_BUTTON_DESCRIPTION_DE');
	define('ADMIN_MAIN_IMAGES', 'ADMIN_MAIN_IMAGES');
	define('ADMIN_MAIN_IMAGES_COUNT', 'ADMIN_MAIN_IMAGES_COUNT');
	define('ADMIN_MAIN_IMAGES_SIZE', 'ADMIN_MAIN_IMAGES_SIZE');
	define('ADMIN_MAIN_IMAGES_DESCRIPTION', 'ADMIN_MAIN_IMAGES_DESCRIPTION');
	define('ADMIN_MAIN_IMAGES_WIDTH', 'ADMIN_MAIN_IMAGES_WIDTH');
	define('ADMIN_MAIN_IMAGES_HEIGHT', 'ADMIN_MAIN_IMAGES_HEIGHT');
	define('ADMIN_MAIN_IMAGE_ASSIGN', 'ADMIN_MAIN_IMAGE_ASSIGN');
	define('ADMIN_BLOG_EMOTIONS', 'ADMIN_BLOG_EMOTIONS');
	define('ADMIN_BLOG_EMITONS_COUNT', 'ADMIN_BLOG_EMITONS_COUNT');
	define('ADMIN_BLOG_EMOTIONS_SIZE', 'ADMIN_BLOG_EMOTIONS_SIZE');
	define('ADMIN_BLOG_EMOTIONS_DESCRIPTION', 'ADMIN_BLOG_EMOTIONS_DESCRIPTION');
	define('ADMIN_BLOG_EMOTIONS_WIDTH', 'ADMIN_BLOG_EMOTIONS_WIDTH');
	define('ADMIN_BLOG_EMOTIONS_HEIGHT', 'ADMIN_BLOG_EMOTIONS_HEIGHT');
	define('ADMIN_CAST', 'ADMIN_CAST');
	define('ADMIN_CAST_COUNT', 'ADMIN_CAST_COUNT');
	define('ADMIN_CAST_SIZE', 'ADMIN_CAST_SIZE');
	define('ADMIN_CAST_DESCRIPTION', 'ADMIN_CAST_DESCRIPTION');
	define('ADMIN_CAST_WIDTH', 'ADMIN_CAST_WIDTH');
	define('ADMIN_CAST_HEIGHT', 'ADMIN_CAST_HEIGHT');
	define('ADMIN_CAST_EN', 'ADMIN_CAST_EN');
	define('ADMIN_CAST_DE', 'ADMIN_CAST_DE');
	define('ADMIN_CAST_LEFT', 'ADMIN_CAST_LEFT');
	define('ADMIN_CAST_RIGHT', 'ADMIN_CAST_RIGHT');
	define('ADMIN_EPISODES', 'ADMIN_EPISODES');
	define('ADMIN_EPISODES_COUNT', 'ADMIN_EPISODES_COUNT');
	define('ADMIN_EPISODES_DESCRIPTION', 'ADMIN_EPISODES_DESCRIPTION');
	define('ADMIN_EPISODES_TITLE_EN', 'ADMIN_EPISODES_TITLE_EN');
	define('ADMIN_EPISODES_TITLE_DE', 'ADMIN_EPISODES_TITLE_DE');
	define('ADMIN_EPISODES_EN', 'ADMIN_EPISODES_EN');
	define('ADMIN_EPISODES_DE', 'ADMIN_EPISODES_DE');
	define('ADMIN_EPISODES_ALT_EN', 'ADMIN_EPISODES_ALT_EN');
	define('ADMIN_EPISODES_ALT_DE', 'ADMIN_EPISODES_ALT_DE');
	define('ADMIN_EPISODES_VIDEO_URL_EN', 'ADMIN_EPISODES_VIDEO_URL_EN');
	define('ADMIN_EPISODES_VIDEO_URL_DE', 'ADMIN_EPISODES_VIDEO_URL_DE');
	define('ADMIN_EPISODES_TYPE', 'ADMIN_EPISODES_TYPE');
	define('ADMIN_EPISODES_SELECT_TYPE', 'ADMIN_EPISODES_SELECT_TYPE');
	define('ADMIN_EPISODES_TYPE_IMAGE', 'ADMIN_EPISODES_TYPE_IMAGE');
	define('ADMIN_EPISODES_TYPE_VIDEO', 'ADMIN_EPISODES_TYPE_VIDEO');
	define('ADMIN_EPISODES_THUMBNAIL', 'ADMIN_EPISODES_THUMBNAIL');

	// Posts
	define('BLOG_POSTS_OLDER', 'BLOG_POSTS_OLDER');
	define('BLOG_POSTS_NEWER', 'BLOG_POSTS_NEWER');
	define('BLOG_POST_OLDER', 'BLOG_POST_OLDER');
	define('BLOG_POST_NEWER', 'BLOG_POST_NEWER');
	define('BLOG_COMMENTS_OLDER', 'BLOG_COMMENTS_OLDER');
	define('BLOG_COMMENTS_NEWER', 'BLOG_COMMENTS_NEWER');
	define('BLOG_DATE_FORMAT', 'BLOG_DATE_FORMAT');
	define('BLOG_EDIT_COMMENT', 'BLOG_EDIT_COMMENT');
	define('BLOG_COMMENT_MODERATION', 'BLOG_COMMENT_MODERATION');
	define('ADMIN_EPISODES_THUMBNAIL', 'ADMIN_EPISODES_THUMBNAIL');

	// Widgets
	define('WIDGED_HARD_SKILL_NAME', 'WIDGED_HARD_SKILL_NAME');
	define('WIDGET_HARD_SKILL_DESCRIPTION', 'WIDGET_HARD_SKILL_DESCRIPTION');
	define('WIDGET_HARD_SKILL_IMAGE', 'WIDGET_HARD_SKILL_IMAGE');
	define('WIDGET_HARD_SKILL_UPLOAD_BUTTON', 'WIDGET_HARD_SKILL_UPLOAD_BUTTON');
	define('WIDGET_HARD_SKILL_IMAGE_ALT', 'WIDGET_HARD_SKILL_IMAGE_ALT');
	define('WIDGET_HARD_SKILL_TITLE', 'WIDGET_HARD_SKILL_TITLE');
	define('WIDGET_HARD_SKILL_DETAILS', 'WIDGET_HARD_SKILL_DETAILS');
	define('WIDGED_PRGORESS_BAR_NAME', 'WIDGED_PRGORESS_BAR_NAME');
	define('WIDGET_PROGRESS_BAR_DESCRIPTION', 'WIDGET_PROGRESS_BAR_DESCRIPTION');
	define('WIDGET_PROGRESS_BAR_IMAGE', 'WIDGET_PROGRESS_BAR_IMAGE');
	define('WIDGET_PROGRESS_BAR_UPLOAD_BUTTON', 'WIDGET_PROGRESS_BAR_UPLOAD_BUTTON');
	define('WIDGET_PROGRESS_BAR_IMAGE_ALT', 'WIDGET_PROGRESS_BAR_IMAGE_ALT');
	define('WIDGET_PROGRESS_BAR_CAPTION', 'WIDGET_PROGRESS_BAR_CAPTION');
	define('WIDGET_PROGRESS_BAR_PERCENTAGE', 'WIDGET_PROGRESS_BAR_PERCENTAGE');
	define('WIDGET_PROGRESS_BAR_SHOW_PERCENTAGE', 'WIDGET_PROGRESS_BAR_SHOW_PERCENTAGE');
	define('WIDGED_GALLERY_NAME', 'WIDGED_GALLERY_NAME');
	define('WIDGET_GALLERY_DESCRIPTION', 'WIDGET_GALLERY_DESCRIPTION');
	define('WIDGET_GALLERY_TITLE', 'WIDGET_GALLERY_TITLE');
	define('WIDGET_GALLERY_IMAGES', 'WIDGET_GALLERY_IMAGES');
	define('WIDGET_GALLERY_UPLOAD_BUTTON', 'WIDGET_GALLERY_UPLOAD_BUTTON');

	// Comments
	define('BLOG_COMMENTS_EMPTY', 'BLOG_COMMENTS_EMPTY');
	define('BLOG_COMMENT_FORM_AUTHOR', 'BLOG_COMMENT_FORM_AUTHOR');
	define('BLOG_COMMENT_FORM_WEBSITE', 'BLOG_COMMENT_FORM_WEBSITE');
	define('BLOG_COMMENT_FORM_PLACEHOLDER', 'BLOG_COMMENT_FORM_PLACEHOLDER');
	define('BLOG_COMMENT_FORM_LOGGED_IN_AS', 'BLOG_COMMENT_FORM_LOGGED_IN_AS');
	define('BLOG_COMMENT_REPLY_HEAD', 'BLOG_COMMENT_REPLY_HEAD');
	define('BLOG_COMMENT_FORM_HEAD', 'BLOG_COMMENT_FORM_HEAD');
	define('BLOG_COMMENT_REPLY_CANCEL', 'BLOG_COMMENT_REPLY_CANCEL');
	define('BLOG_COMMENT_SUBMIT', 'BLOG_COMMENT_SUBMIT');
	define('BLOG_COMMENT_FORM_LOGOUT', 'BLOG_COMMENT_FORM_LOGOUT');

	// Headers
	define('HEADER_COMIC', 'HEADER_COMIC');
	define('HEADER_GAME', 'HEADER_GAME');
	define('HEADER_BLOG', 'HEADER_BLOG');
	define('HEADER_MAIN', 'HEADER_MAIN');

	// Misc
	define('SINGLE_TO_TOP', 'SINGLE_TO_TOP');



	function tnet_register_strings()
	{
		tnet_reg(HEADER_COMIC);
		tnet_reg(HEADER_GAME);
		tnet_reg(HEADER_BLOG);
		tnet_reg(HEADER_MAIN);

		tnet_reg(BLOG_COMMENTS_EMPTY);
		tnet_reg(BLOG_COMMENT_FORM_AUTHOR);
		tnet_reg(BLOG_COMMENT_FORM_WEBSITE);
		tnet_reg(BLOG_COMMENT_FORM_PLACEHOLDER);
		tnet_reg(BLOG_COMMENT_FORM_LOGGED_IN_AS);
		tnet_reg(BLOG_COMMENT_FORM_HEAD);
		tnet_reg(BLOG_COMMENT_REPLY_HEAD);
		tnet_reg(BLOG_COMMENT_REPLY_CANCEL);
		tnet_reg(BLOG_COMMENT_SUBMIT);
		tnet_reg(BLOG_COMMENT_FORM_LOGOUT);

		tnet_reg(WIDGED_HARD_SKILL_NAME);
		tnet_reg(WIDGET_HARD_SKILL_DESCRIPTION);
		tnet_reg(WIDGET_HARD_SKILL_IMAGE);
		tnet_reg(WIDGET_HARD_SKILL_UPLOAD_BUTTON);
		tnet_reg(WIDGET_HARD_SKILL_IMAGE_ALT);
		tnet_reg(WIDGET_HARD_SKILL_TITLE);
		tnet_reg(WIDGET_HARD_SKILL_DETAILS);
		tnet_reg(WIDGED_PRGORESS_BAR_NAME);
		tnet_reg(WIDGET_PROGRESS_BAR_DESCRIPTION);
		tnet_reg(WIDGET_PROGRESS_BAR_IMAGE);
		tnet_reg(WIDGET_PROGRESS_BAR_UPLOAD_BUTTON);
		tnet_reg(WIDGET_PROGRESS_BAR_IMAGE_ALT);
		tnet_reg(WIDGET_PROGRESS_BAR_CAPTION);
		tnet_reg(WIDGET_PROGRESS_BAR_PERCENTAGE);
		tnet_reg(WIDGET_PROGRESS_BAR_SHOW_PERCENTAGE);
		tnet_reg(WIDGED_GALLERY_NAME);
		tnet_reg(WIDGET_GALLERY_DESCRIPTION);
		tnet_reg(WIDGET_GALLERY_TITLE);
		tnet_reg(WIDGET_GALLERY_IMAGES);
		tnet_reg(WIDGET_GALLERY_UPLOAD_BUTTON);

		tnet_reg(BLOG_POSTS_OLDER);
		tnet_reg(BLOG_POSTS_NEWER);
		tnet_reg(BLOG_POST_OLDER);
		tnet_reg(BLOG_POST_NEWER);
		tnet_reg(BLOG_COMMENTS_OLDER);
		tnet_reg(BLOG_COMMENTS_NEWER);
		tnet_reg(BLOG_DATE_FORMAT);
		tnet_reg(BLOG_EDIT_COMMENT);
		tnet_reg(BLOG_COMMENT_MODERATION);
		tnet_reg(ADMIN_EPISODES_THUMBNAIL);

		tnet_reg(ADMIN_TITLE);
		tnet_reg(ADMIN_MENU);
		tnet_reg(ADMIN_MAIN_TITLE);
		tnet_reg(ADMIN_MAIN_MENU);
		tnet_reg(ADMIN_BLOG_TITLE);
		tnet_reg(ADMIN_BLOG_MENU);
		tnet_reg(ADMIN_CAST_TITLE);
		tnet_reg(ADMIN_CAST_MENU);
		tnet_reg(ADMIN_EPISODES_TITLE);
		tnet_reg(ADMIN_EPISODES_MENU);
		tnet_reg(ADMIN_MEDIA_LIBRARY_USE);
		tnet_reg(ADMIN_OPTIONS);
		tnet_reg(ADMIN_GENERAL);
		tnet_reg(ADMIN_SOCIAL_BUTTON_COUNT);
		tnet_reg(ADMIN_SOCIAL_BUTTON_IMAGE_SIZE);
		tnet_reg(ADMIN_SOCIAL_BUTTON_LABEL);
		tnet_reg(ADMIN_SOCIAL_BUTTON_DESCRIPTION);
		tnet_reg(ADMIN_SOCIAL_BUTTON_GRAPHICS);
		tnet_reg(ADMIN_SOCIAL_BUTTON_UP_IMAGE);
		tnet_reg(ADMIN_SOCIAL_BUTTON_DOWN_IMAGE);
		tnet_reg(ADMIN_SOCIAL_BUTTON_URL_EN);
		tnet_reg(ADMIN_SOCIAL_BUTTON_URL_DE);
		tnet_reg(ADMIN_SOCIAL_BUTTON_DESCRIPTION_EN);
		tnet_reg(ADMIN_SOCIAL_BUTTON_DESCRIPTION_DE);
		tnet_reg(ADMIN_MAIN_IMAGES);
		tnet_reg(ADMIN_MAIN_IMAGES_COUNT);
		tnet_reg(ADMIN_MAIN_IMAGES_SIZE);
		tnet_reg(ADMIN_MAIN_IMAGES_DESCRIPTION);
		tnet_reg(ADMIN_MAIN_IMAGES_WIDTH);
		tnet_reg(ADMIN_MAIN_IMAGES_HEIGHT);
		tnet_reg(ADMIN_MAIN_IMAGE_ASSIGN);
		tnet_reg(ADMIN_BLOG_EMOTIONS);
		tnet_reg(ADMIN_BLOG_EMITONS_COUNT);
		tnet_reg(ADMIN_BLOG_EMOTIONS_SIZE);
		tnet_reg(ADMIN_BLOG_EMOTIONS_DESCRIPTION);
		tnet_reg(ADMIN_BLOG_EMOTIONS_WIDTH);
		tnet_reg(ADMIN_BLOG_EMOTIONS_HEIGHT);
		tnet_reg(ADMIN_CAST);
		tnet_reg(ADMIN_CAST_COUNT);
		tnet_reg(ADMIN_CAST_SIZE);
		tnet_reg(ADMIN_CAST_DESCRIPTION);
		tnet_reg(ADMIN_CAST_WIDTH);
		tnet_reg(ADMIN_CAST_HEIGHT);
		tnet_reg(ADMIN_CAST_EN);
		tnet_reg(ADMIN_CAST_DE);
		tnet_reg(ADMIN_CAST_LEFT);
		tnet_reg(ADMIN_CAST_RIGHT);
		tnet_reg(ADMIN_EPISODES);
		tnet_reg(ADMIN_EPISODES_COUNT);
		tnet_reg(ADMIN_EPISODES_DESCRIPTION);
		tnet_reg(ADMIN_EPISODES_TITLE_EN);
		tnet_reg(ADMIN_EPISODES_TITLE_DE);
		tnet_reg(ADMIN_EPISODES_EN);
		tnet_reg(ADMIN_EPISODES_DE);
		tnet_reg(ADMIN_EPISODES_ALT_EN);
		tnet_reg(ADMIN_EPISODES_ALT_DE);
		tnet_reg(ADMIN_EPISODES_VIDEO_URL_EN);
		tnet_reg(ADMIN_EPISODES_VIDEO_URL_DE);
		tnet_reg(ADMIN_EPISODES_TYPE);
		tnet_reg(ADMIN_EPISODES_SELECT_TYPE);
		tnet_reg(ADMIN_EPISODES_TYPE_IMAGE);
		tnet_reg(ADMIN_EPISODES_TYPE_VIDEO);
		tnet_reg(ADMIN_EPISODES_THUMBNAIL);

		tnet_reg(COOKIE_TITLE_TEXT);
		tnet_reg(COOKIE_CONSENT_TEXT);
		tnet_reg(COOKIE_ACCEPT_TEXT);

		tnet_reg(FOOTER_CONTACT_HEAD);
		tnet_reg(FOOTER_MAIL);
		tnet_reg(FOOTER_DISCORD);
		tnet_reg(FOOTER_DISCORD_SERVER);
		tnet_reg(FOOTER_SOCIAL_HEAD);
		tnet_reg(FOOTER_LEGAL_HEAD);
		tnet_reg(FOOTER_LEGAL);
		tnet_reg(FOOTER_DATA);
		tnet_reg(FOOTER_LICENSE);

		tnet_reg(PORTFOLIO_TITLE);
		tnet_reg(PORTFOLIO_SUBTITLE);
		tnet_reg(PORTFOLIO_PRIVATE_TAB);
		tnet_reg(PORTFOLIO_PROFESSIONAL_TAB);
		tnet_reg(PORTFOLIO_BACK_TAB);
		tnet_reg(PORTFOLIO_UNLOCK_PROJECT_TITLE);
		tnet_reg(PORTFOLIO_UNLOCK_TITLE);
		tnet_reg(PORTFOLIO_UNLOCK_DESCRIPTION);
		tnet_reg(PORTFOLIO_UNLOCK_LABEL);
		tnet_reg(PORTFOLIO_UNLOCK_PLACEHOLDER);
		tnet_reg(PORTFOLIO_UNLOCK_SUBMIT);
		tnet_reg(PORTFOLIO_UNLOCK_INVALID);
		tnet_reg(PORTFOLIO_BOTTOM_BACK);

		tnet_reg(COMIC_NO_EPISODES);
		tnet_reg(COMIC_NAV_FIRST);
		tnet_reg(COMIC_NAV_PREVIOUS);
		tnet_reg(COMIC_NAV_NEXT);
		tnet_reg(COMIC_NAV_LAST);
		tnet_reg(COMIC_ARCHIVE_HEADLINE);
		tnet_reg(COMIC_ARCHIVE_SUBTITLE);

		tnet_reg(SINGLE_TO_TOP);
		tnet_reg(BLOG_COMMENTS_EMPTY);
	}

	function tnet_reg($const) { pll_register_string($const, $const, 'tnet'); }



	function tnet_pl($const) { return esc_html(pll__($const)); }
	function tnet_e($const) { esc_html_e(pll__($const)); }
	function tnet_attr_pl($const) { esc_attr(pll__($const)); }
	function tnet_attr_e($const) { esc_attr_e(pll__($const)); }
?>